### ISSUE TITLE
Use composer 2 in the php-7.4 image for faster installation times

### ISSUE THREAD

**Issue by Aimless321** [extdn/github-actions-m2#25]
Since Magento 2.4 is the only Magento version that is compatible with php 7.4, I think it would be possible to switch the composer version for the php 7.4 image to version 2 without breaking backwards compatibility.

This would speedup the installation of Magento and additional packages significantly, and thus make the action a lot faster.

Please let me know what you think, and if necessary I can make a PR.

**Comment by fooman** [comment]
hi @Aimless321 thanks for the suggestion. Composer 2.0 is only possible from Magento 2.4.2 so we would still have the 2.4.1 and 2.4.0 versions on php 7.4.

I believe projects like warden essentially now include both versions which may be something we can follow and then decide and runtime which phar to use.

**Comment by Aimless321** [comment]
Ah that's unfortunate, I wasn't aware of that.

It would be great if it could be specified with an input, but i'm not sure how difficult that would be to implement.

**Comment by jissereitsma** [comment]
Indeed, a variable `COMPOSER_VERSION` would be awesome, so that you can determine yourself what to use. The current composer integration is made possible by copying (`COPY`) composer into the Docker file. To my understanding, this approach will not allow for the switching part. Instead, either a different Docker image needs to be used, or the composer download needs to be picked up by the entrypoint script ...

**Comment by jissereitsma** [comment]
I'm closing this ticket because the mentioned functionality is now merged.
