### ISSUE TITLE
Magento-phpstan Action: Why do we need a composer package for it? Composer 2.0 is not supported!

### ISSUE THREAD

**Issue by trunglv** [extdn/github-actions-m2#49]
Hi, thank you for your great works here.
I would like to have 2 questions: 
1. Why do we need a composer package for it? 
2. Can you pls update a docker? so it can support Composer 2.0.
Thank you so much!

**Comment by jissereitsma** [comment]
Actually, the goal of ExtDN (under which this repository falls) has been to offer testing for third party extensions (ExtDN = Extension Developer Network). And composer is kind-of an essential requirement for offering an extension to others. Are you bumping into issues because of this?

As for composer 2 support, indeed this is still missing. It was pending another PR https://github.com/extdn/github-actions-m2/pull/40/files which we wanted to await first. Let me see if I can fix this quickly here as well.

**Comment by jissereitsma** [comment]
Added composer 2 support, even though the default is still composer 1. The following example explains how to enable composer 2 with the flag `COMPOSER_VERSION`: https://github.com/extdn/github-actions-m2/blob/master/examples/extdn-phpstan.yml I didn't check if this is fully working yet though ....

**Comment by trunglv** [comment]
Hi @jissereitsma. Thank you. Yes, I checked again, it worked well with packages on Composer 2.0. 
> Actually, the goal of ExtDN (under which this repository falls) has been to offer testing for third party extensions (ExtDN = Extension Developer Network). And composer is kind-of an essential requirement for offering an extension to others. Are you bumping into issues because of this?
=> It's good idea. I have an issue that makes the testing work with private Repo. Your Github action is very super good to get started. I will learn from it and bring it to an adjustment version that works on private Repo.

**Comment by jissereitsma** [comment]
I'm closing this ticket for now. Let me know if it needs to be reopened.
