### ISSUE TITLE
[BUG] Magento 2 Tests Integration tests fail unless the key USE_OVERRIDE_CONFIG is set to enabled in `phpunit.xml`

### ISSUE THREAD

**Issue by damienwebdev** [extdn/github-actions-m2#56]
See the [phpunit.xml.dist](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/phpunit.xml.dist#L87)

To be perfectly honest, this configuration setting is beyond me. I spent an hour with @MateusDadalto (after he spent a whole day) trying to understand this configuration settings purpose is.

In short, it looks like during a test run in `dev/tests/integration` in v2.4.3, Magento installs some modules into `app/code/Magento`. 

After test cleanup

1. These extraneous test module files are deleted
2. Magento also triggers a `session_close` 
3 `session_close` triggers a native Magento 2 plugin to retrieve a value from `ScopeConfigInterface`
4. `getValue` triggers a config merge 
5. Config merge does a `fopen` on a now deleted file `app/code/Magento/TestModuleFakePaymentMethod/etc/config.xml`

```bash
Fatal error: Uncaught Magento\Framework\Exception\FileSystemException: The "/tmp/m2/app/code/Magento/TestModuleFakePaymentMethod/etc/config.xml" file doesn't exist. in /tmp/m2/vendor/magento/framework/Filesystem/File/Read.php:76
Stack trace:
#0 /tmp/m2/vendor/magento/framework/Filesystem/File/Read.php(62): Magento\Framework\Filesystem\File\Read->assertValid()
#1 /tmp/m2/vendor/magento/framework/Filesystem/File/Read.php(52): Magento\Framework\Filesystem\File\Read->open()
#2 /tmp/m2/vendor/magento/framework/Filesystem/File/ReadFactory.php(45): Magento\Framework\Filesystem\File\Read->__construct('/tmp/m2/app/cod...', Object(Magento\Framework\Filesystem\Driver\File))
#3 /tmp/m2/vendor/magento/framework/Config/FileIterator.php(70): Magento\Framework\Filesystem\File\ReadFactory->create('/tmp/m2/app/cod...', 'file')
#4 /tmp/m2/vendor/magento/framework/App/Config/Initial/Reader.php(93): Magento\Framework\Config\FileIterator->current()
#5 /tmp/m2/vendor/magento/module-config/App/Config/Source/ModularConfigSource.php(42): Magento\F in /tmp/m2/vendor/magento/framework/Filesystem/File/Read.php on line 76
```

Regardless, we need the `USE_OVERRIDE_CONFIG` in the phpunit.xml because of reasons.

**Comment by jissereitsma** [comment]
Hmm, that's strange. I'm not using `USE_OVERRIDE_CONFIG` anywhere in my integration tests: Not in my GitHub Actions and not in my local environment. Also, I've been using 2.4.3 and 2.4.3-p1 in both cases, and not bumping into this same issue. But are you saying that this issue is also stopping you from using the GitHub Actions of ExtDN? If so, it would be good to compare YAML files for starters.

**Comment by damienwebdev** [comment]
I can't repro this any more.

**Comment by hnsr** [comment]
In one of my projects, I was suddenly getting this error when running integration tests through github actions. Same backtrace as the one @damienwebdev provided.

It is a bit puzzling why this happens for me. Both the module clean up logic (https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/deployTestModules.php#L51-L59), as well as the session clean up logic (https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Session/SessionManager.php#L217), are done via shutdown functions, which should always be called in the order in which they are registered, and the order is presumably always the same and module clean up always happens first.

I suspect the issue is that somewhere we are doing or causing a cache clear in one of our tests, which later causes the session save handler to trigger a config load when it calls `\Magento\Framework\Session\SessionMaxSizeConfig::getSessionMaxSize` to determine the max session size.

Either way, as a quick workaround, I've enabled the `TESTS_PARALLEL_RUN` config in our `phpunit.xml`, which prevents module clean up.
