### ISSUE TITLE
Feat: Support PHP 8.1 Actions

### ISSUE THREAD

**Issue by damienwebdev** [extdn/github-actions-m2#63]

**Comment by jissereitsma** [comment]
I've wildly added PHP 8.1 support but haven't checked for the details yet. Could you see how far you can run things? I hope to dive into this myself next week.

**Comment by BorisovskiP** [comment]
@jissereitsma i also encountered an issue where if you use `uses: extdn/github-actions-m2/magento-integration-tests/8.1@master` then the action will fail because it cannot find the docker image (`Error response from daemon: manifest for extdn/magento-integration-tests-action:8.1-latest not found: manifest unknown: manifest unknown`)

**Comment by sprankhub** [comment]
I think @jissereitsma needs to publish a new release, so that https://github.com/extdn/github-actions-m2/blob/master/.github/workflows/docker.yml is run and the new PHP 8.1 Docker images are built.

**Comment by jissereitsma** [comment]
Could you recheck? I've been using PHP 8.1 with integration tests successfully in the last ... 10 days or so. It should be working. If not, could you post your extension or otherwise the workflow YAML involved?

**Comment by sprankhub** [comment]
The images are indeed present now. @damienwebdev, could you verify that it works for you now?

**Comment by damienwebdev** [comment]
LGTM
